server.port=8082

# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/food_order_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=Shanthosh@123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
# Prevent JPA session from being held open on Camunda worker threads
spring.jpa.open-in-view=false

# Camunda External Task Client Configuration
camunda.bpm.client.base-url=http://localhost:8081/engine-rest
camunda.bpm.client.lock-duration=30000
camunda.bpm.client.async-response-timeout=10000
# Subscribe to topic: payment-processing
camunda.bpm.client.subscriptions.payment-processing.variable-names=orderId,customerName,item,amount
camunda.bpm.client.subscriptions.payment-processing.process-definition-key=order-processing
